### ISSUE TITLE
Error when launching the container from docker compose

### ISSUE THREAD

**Issue by jonny190** [DeepWoods/nxfilter-docker#1]
**Error**
Creating nxfilter_nxfilter_1 ... done
Attaching to nxfilter_nxfilter_1
nxfilter_1  | Exception in thread "main" java.lang.NullPointerException
nxfilter_1  |   at nxd.Main.<init>(Unknown Source)
nxfilter_1  |   at nxd.Main.main(Unknown Source)
nxfilter_1  | Exception in thread "Thread-0" java.lang.NullPointerException
nxfilter_1  |   at nxd.n.run(Unknown Source)

**This is based on the below docker compose**

version: '3.3'
services:
  nxfilter:
    image: deepwoods/nxfilter:latest
    hostname: nxfilter
    volumes:
      - /data/nxfinter/nxfilter-conf:/nxfilter/conf
      - /data/nxfinter/nxfilter-log:/nxfilter/log
      - /data/nxfinter/nxfilter-db:/nxfilter/db
    restart: unless-stopped
    environment:
      TZ: "Europe/London"
    networks:
      lan:
        ipv4_address: *.*.*.* (Ip address redacted)
networks:
  lan:
    external:
      name: lan

**Comment by DeepWoods** [comment]
More than likely it's a system permissions issue with your volume mapping.  NxFilter runs with root privileges in the container to be able to bind to the TCP and UPD ports required.  Java may also but I'm not sure of that one.  For my Debian 11 test system, I use this docker compose which maps the volumes to /var/lib/docker/volumes/compose_nxf*  The file owner/group in the _data directories there are a mix of root and my personal user.  

```
version: '3.5'

services:
  nxfilter:
    image: deepwoods/nxfilter:latest
    container_name: nxfilter
    hostname: nxfilter
    restart: unless-stopped
    environment:
      TZ: "America/Chicago"
    volumes:
      - nxfconf:/nxfilter/conf
      - nxflog:/nxfilter/log
      - nxfdb:/nxfilter/db
    ports:
      - 53:53/udp
      - 80:80
      - 443:443
      - 19002-19004:19002-19004
volumes:
  nxfconf:
  nxfdb:
  nxflog:
```
