### ISSUE TITLE
Issue to start docker compose

### ISSUE THREAD

**Issue by killmasta93** [DeepWoods/nxfilter-docker#2]
Hi @DeepWoods 
Currently checking out the docker compose but when i try im getting
`
Error response from daemon: driver failed programming external connectivity on endpoint nxfilter (536d8410fcb8fef80b8d54d0e73647d1974d2303487235d4644adce02a7625b2): Error starting userland proxy: listen udp4 0.0.0.0:53: bind: address already in use
`
i was able to solve this by running this 
`
  sudo systemctl stop systemd-resolved `

but not sure whats the correct way?

```
version: '3.5'

services:
  nxfilter:
    image: deepwoods/nxfilter:latest
    container_name: nxfilter
    hostname: nxfilter
    restart: unless-stopped
    environment:
      TZ: "America/Bogota"
    volumes:
      - nxfconf:/nxfilter/conf
      - nxflog:/nxfilter/log
      - nxfdb:/nxfilter/db
    ports:
      - 53:53/udp
      - 19004:19004/udp
      - 80:80
      - 443:443
      - 19002-19004:19002-19004
volumes:
  nxfconf:
   driver: local-persist
   driver_opts:
     mountpoint: /scsi1/nxfilter/nxfconf
  nxflog:
   driver: local-persist
   driver_opts:
     mountpoint: /scsi1/nxfilter/nxflog
  nxfdb:
   driver: local-persist
   driver_opts:
     mountpoint: /scsi1/nxfilter/nxfdb
```

also when trying to connect a client using the nxproxy im getting this issue not sure what else i missed?

![image](https://github.com/DeepWoods/nxfilter-docker/assets/13953629/142915db-0192-4040-be70-7e506a089998)
